### ISSUE TITLE
Prefix or suffix for filenames

### ISSUE THREAD

**Issue by agnoldo** [piqoni/matcha#10]
Dear @piqoni , thanks again for the great work! I was using Matcha here and I was wondering if you consider viable and interesting to add prefix and/or suffix to daily notes generated. My point is to avoid name clash inside Obsidian databases if we use Matcha daily notes in conjunction with other Daily Notes.

Have a nice day!

**Comment by piqoni** [comment]
Yeah it makes perfect sense for the user to have control on that. 

But, I also use daily notes and never encountered this issue. I have created a directory called "brew" (like a Daily Brew) where Matcha generates the rss. And everyday all I have to do is: 
Search by "brew" and current day always come up first, so all I have to do is press 'Enter'
![image](https://user-images.githubusercontent.com/3144671/210736973-548c3ca6-e553-4f94-87bc-07c969449f22.png)

**Comment by piqoni** [comment]
So, in a way "a directory" can also be "prefix" in this context.

**Comment by agnoldo** [comment]
Yes, totally agreed, @piqoni. And users can change the name of the daily note instead of the brew (RSS) note. In my case I just didn't want to bother with them because I already have 200+ daily notes since 2021 with names YYYY-MM-DD.md and now I'm using Matcha and Templater to import your daily note to my old daily note (which is more on a GTD style).

Thanks!

**Comment by piqoni** [comment]
Added in https://github.com/piqoni/matcha/pull/15 :)

**Comment by agnoldo** [comment]
Dear @piqoni , thanks for the implementation! Already tested successfully in Windows. Simplified a lot my workflow here!
