### ISSUE TITLE
windows paths not working and...

### ISSUE THREAD

**Issue by pcause** [piqoni/matcha#19]
tried with a windows path and not working. 

where do you store the history/last time run.  want to delete that so I can test more options

**Comment by piqoni** [comment]
Hi @pcause, thanks for testing out!
1. Do you have any error on the first one or it just doesn't produce the markdown files? 

2. Not sure what you mean here. The app stores the "seen articles" by in a sqlite database in (theoretically) C:\Users\<username>\AppData\brew\matcha.db for windows. But no datetime info.

**Comment by piqoni** [comment]
Hi @pcause, 

I tried on a windows machine, and it works just fine. Are you sure you used the last release? 
I used the following configuration:
markdown_dir_path: C:\Users\myuser\

And markdown was generated accordingly :) 

Will close this unless you can help me reproduce
