### ISSUE TITLE
markdown shouldn't use <br> to separate lines.

### ISSUE THREAD

**Issue by pcause** [piqoni/matcha#20]
In markdown to end a line as though you'd entered a new line on a text file, you end the line with 2 spaces then the newline.  You can see it right here in the stuff below

first line  
second line

where as using br's get you:

first line<br>
second line<br>

**Comment by pcause** [comment]
in obsidian

**Comment by piqoni** [comment]
Fixed it here: https://github.com/piqoni/matcha/commit/3cfd151224a2d698ddf0e924da82642df568b5b0
next release will have it :) 

Thanks for reporting it!

**Comment by piqoni** [comment]
FYI: New release has this change: https://github.com/piqoni/matcha/releases/tag/v0.5.2
