### ISSUE TITLE
Inquiry: Does Matcha support Social Media RSS Feeds

### ISSUE THREAD

**Issue by Feranmi-Star90** [piqoni/matcha#21]
I added Reddit RSS Feeds to my config files but they are not working, YouTube works fine but I can't other feeds from Twitter or Reddit to work. 

Thanks

**Comment by piqoni** [comment]
I'll investigate Reddit (I think they apply some rate-limits and depending on user agent). 

Twitter does not support RSS but for twitter I use any of Nitter instances. 
Basically find an instance with good uptime here: https://github.com/xnaas/nitter-instances
And visit it and put the twitter handle in the main search box, then on their Nitter profile, top right, there is the RSS feed". It works great.

**Comment by Feranmi-Star90** [comment]
Oh okay, I see. Thank you very much. 🙏🏾

**Comment by piqoni** [comment]
As per reddit RSS, I see it works now :) 

I tried with a couple, this one being one: 
https://www.reddit.com/r/golang.rss
