### ISSUE TITLE
Images and hyperlinks on the terminal

### ISSUE THREAD

**Issue by rogerfedererforever** [piqoni/matcha#26]
can‘t display images and hyperlinks on the terminal? Thanks
![matcha](https://user-images.githubusercontent.com/104702947/232656391-81940223-c442-4ca6-8199-d330f0c0ae9e.png)

**Comment by piqoni** [comment]
Hi there, what OS and what Terminal you are using?

**Comment by rogerfedererforever** [comment]
It's ok now. Thanks
![matcha](https://user-images.githubusercontent.com/104702947/233287513-d502e68f-0c82-4e70-a942-7a26bf6c3f14.png)
