### ISSUE TITLE
OpenAssistant as an underlying AI model

### ISSUE THREAD

**Issue by erkinalp** [piqoni/matcha#29]
[OpenAssistant](https://open-assistant.io) is an open source AI assistant trained with open data.

**Comment by piqoni** [comment]
I couldn't find any API to reach OA as of yet. Maybe when there is an API published this can be considered. 
Let me know if there is an API and I somehow missed it.

**Comment by piqoni** [comment]
See latest version which has support for local AI models: https://github.com/piqoni/matcha/releases/tag/v0.6.1
