### ISSUE TITLE
OPML and categories

### ISSUE THREAD

**Issue by pcause** [piqoni/matcha#3]
add an ability for the config to speficy an opml file that has the feeds.  Support categories with feeds within the categories.  A category is a directory and the feed is a page within the category.  Allows easy importing of existing RSS feeds from other readers.

**Comment by piqoni** [comment]
Absolutely, and OPML is on the roadmap.

**Comment by piqoni** [comment]
I added basic OPML support here: https://github.com/piqoni/matcha/commit/ea75982e5e0ee5fbc281e66efe659ef899418075
For now, you need to call your opml file `config.opml` and leave it in the current directory where matcha is located. 
I will add the release binaries tomorrow.

For the time being, I'm not sure about the categories and creating directories for each category suggestion. I think having a single daily file for everything is more convenient and a good feature in itself (also its a digest, so everyday these pages are reset and not very big). Certainly though, I will add a separate heading for each category.
