### ISSUE TITLE
Cache database stored in local folder (multiplatform support)

### ISSUE THREAD

**Issue by agnoldo** [piqoni/matcha#30]
Dear Piqoni,

Thanks again for your tool, which is amazing. I use it a lot and this suggestion is very small. The case is that I use matcha inside an Obsidian vault that is synced through cloud. So sometimes I use matcha in other computers also and then the tool uses an outdated cache database (I totally get it). If it`s possible and easy, I would like to suggest allowing the user to change where the cache database is, so it can be also synced through cloud.

Best regards,

Arnaldo

**Comment by piqoni** [comment]
Sounds like a very good idea, so will implement it soon.

**Comment by piqoni** [comment]
Added this today https://github.com/piqoni/matcha/releases/tag/v0.5.7

Usage: 
In config.yaml add: 
`database_file_path: /Users/myuser/matcha.db
`

Let me know how it goes :)

**Comment by agnoldo** [comment]
Thank you, @piqoni. Amazing!
