### ISSUE TITLE
Build an Obsidian plugin for the project

### ISSUE THREAD

**Issue by kappq** [piqoni/matcha#33]
I've recently started using Matcha to generate my daily digest. The generation works amazingly, however I found the setup process to be a bit tedious as it requires various steps and manual configuration. I believe that the integration with the Obsidian editor could be greatly improved through the creation of a plugin.

1. The plugin will be available for installation directly from the Obsidian community plugins interface, simplifying the setup process for users.
2. Configuration can be achieved through the plugin settings.
3. The plugin will be designed to automatically run whenever the user opens their Obsidian vault.
4. Additionally, users will have the option to manually trigger the plugin by executing an Obsidian command.

The plugin would have several benefits. It provides easier installation through Obsidian's plugin interface, simplifies configuration with a user-friendly settings interface, seamlessly integrates with Obsidian and will, hopefully, be able to reach a broader audience.

I would love to contribute to bring this plugin to life, hoping to improve user experience within Obsidian and make this awesome project even better. I don't have any previous experience with Obsidian plugins, but I'm always down to learn something new.

Please let me know if there is any additional information or clarification required. I look forward to working on this. 😀

**Comment by piqoni** [comment]
Hi there, 

It's a great idea, but Im personally not familiar with Obsidian plugin system and I'd rather keep matcha as a tool-agnostic markdown generator. Im pretty sure people over at [Obsidian community](https://obsidian.md/community) could be interested in building one, so you can probably post this post also there :)
