### ISSUE TITLE
Feature request: use go routines for fetching feeds concurrently 

### ISSUE THREAD

**Issue by barakplasma** [piqoni/matcha#41]
I half implemented concurrent feed downloads, and it speeds up matcha significantly when there are a lot of feeds.

I implemented it, but I haven't figured out how to close the channel of items. I can open a PR later if you're interested in this contribution.

**Comment by CalabashSquash** [comment]
I personally would be interested in this, and can help you debug the problem you mentioned :100:

**Comment by piqoni** [comment]
May I know what is the use case, ie, the way I use the tool is to generate markdowns in background and I read the markdown files whenever? Or do you want to use the terminal mode and you are not happy with the sequential load of items?

**Comment by piqoni** [comment]
Oh and if its the terminal mode, I actually just pushed a new simple project that concentrates on speed (background pre-fetching of article content) https://github.com/piqoni/cast-text
But currently its supports only one rss feed, so its more for news outlets, so not exactly matcha but similar in nature.

**Comment by barakplasma** [comment]
I have a _lot_ of feeds (100s), and haven't yet added matcha to my task scheduler. So I felt the loading time for matcha to download each feed sequentially with blocking io.

I like the look of the terminal reader too, I'll check it out.
