### ISSUE TITLE
config file entries can't be deleted, causes error

### ISSUE THREAD

**Issue by pcause** [piqoni/matcha#6]
- if I delete a config file entry, like weath entries the app exits with an error and no message
- on Windows can't seem to enter a path that doesn't cause a fault.  trued c:\foo , /c/foo, c:/foo

**Comment by piqoni** [comment]
The second point will be addressed in the other issue you opened. The first one is a good idea!

**Comment by piqoni** [comment]
Fixed here: 
https://github.com/piqoni/matcha/commit/a405ac1d375c16892cb5dedc011cb3f0ea749c00

**Comment by piqoni** [comment]
Only feeds are now mandatory (could be made optional but felt a corner case to use the app with only google keywords option)

**Comment by pcause** [comment]
how about adding an opml filename to the config?  if specified you use that otherwise look for the config.opml.  NOTE that it is the name of the file, not the directory.  Then one could have feeds, feeds plus opml, or just one of feed/opml.

**Comment by piqoni** [comment]
> how about adding an opml filename to the config?

Fixed in https://github.com/piqoni/matcha/pull/13
